name: Test CI
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  ️
        uses: actions/checkout@v2.3.1

      - name: lock npm version
        uses: actions/setup-node@v3
        with:
          node-version: 16.20.0

      - name: Install and Build
        run: |
          npm i -g pnpm@8
          pnpm run init
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: test
        run: |
          pnpm run test
